// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmzAim6IIhaTBX4I979ApjQvaGU2o2J78',
    appId: '1:102125826160:web:62f17026f02595f2ec44b5',
    messagingSenderId: '102125826160',
    projectId: 'ecommercet-2eba7',
    authDomain: 'ecommercet-2eba7.firebaseapp.com',
    storageBucket: 'ecommercet-2eba7.firebasestorage.app',
    measurementId: 'G-424NCLGLRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU78g1wpwWT0WoXXFfPs9oWrYGoPxBfAk',
    appId: '1:102125826160:android:8f0b8475b97c4a6fec44b5',
    messagingSenderId: '102125826160',
    projectId: 'ecommercet-2eba7',
    storageBucket: 'ecommercet-2eba7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9KYMk74k9YMIreMlhKzIsyVjAxhUFTXA',
    appId: '1:102125826160:ios:2228c94e0a40c5ffec44b5',
    messagingSenderId: '102125826160',
    projectId: 'ecommercet-2eba7',
    storageBucket: 'ecommercet-2eba7.firebasestorage.app',
    iosBundleId: 'com.example.ecommercet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9KYMk74k9YMIreMlhKzIsyVjAxhUFTXA',
    appId: '1:102125826160:ios:2228c94e0a40c5ffec44b5',
    messagingSenderId: '102125826160',
    projectId: 'ecommercet-2eba7',
    storageBucket: 'ecommercet-2eba7.firebasestorage.app',
    iosBundleId: 'com.example.ecommercet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmzAim6IIhaTBX4I979ApjQvaGU2o2J78',
    appId: '1:102125826160:web:b02fadba10122a6eec44b5',
    messagingSenderId: '102125826160',
    projectId: 'ecommercet-2eba7',
    authDomain: 'ecommercet-2eba7.firebaseapp.com',
    storageBucket: 'ecommercet-2eba7.firebasestorage.app',
    measurementId: 'G-1W5WV0WY4F',
  );
}
